V 01
evil-star/carsharing pull request #1
Opened 2022-03-20 09:20 UTC by evil-star

2022-03-21 12:53 UTC, EvgeniyaFilatova requested changes

2022-03-21 12:53 UTC, EvgeniyaFilatova commented on src/App.tsx
> +  useEffect(() => {
- [ ] А зачем таким образом устанавливать высоту? Разве нельзя через css это сделать что-то типа: height: 100vh

2022-03-21 12:53 UTC, EvgeniyaFilatova commented on src/App.tsx
> +                <React.Suspense fallback={<>...</>}>
- [ ] Suspense разве не экспериментальная возможность? Используй только те вещи, которые есть в стабильной версии

2022-03-21 12:53 UTC, EvgeniyaFilatova commented on src/assets/fonts/Roboto/roboto.css
> +@font-face {
- [ ] Нужно ли в проекте так много шрифтов? Мне кажется, 2/3 не встретится, так что можно их не подключать

2022-03-21 12:53 UTC, EvgeniyaFilatova commented on src/common/components/HeroSlider/HeroSlider.tsx
> +  const SlickArrowLeft = ({ currentSlide, slideCount, ...props }: any) => (
- [ ] Не используй any, старайся всё строго типизировать. И нужны ли тебе вообще здесь эти пропсы? Не вижу смысла в них

2022-03-21 12:53 UTC, EvgeniyaFilatova commented on src/common/components/HeroSlider/HeroSlider.tsx
> +  const SlickArrowRight = ({ currentSlide, slideCount, ...props }: any) => (
- [ ] То же самое

2022-03-21 12:53 UTC, EvgeniyaFilatova commented on src/common/components/HeroSlider/HeroSlider.tsx
> +      {slides.map((s, idx) => (
- [ ] Старайся везде использовать осмысленные названия для переменных. Здесь, например, лучше назвать slide. Так другим разработчикам, разбирающимся в твоем коде, будет намного легче воспринимать его

2022-03-21 12:53 UTC, EvgeniyaFilatova commented on src/common/components/HeroSlider/HeroSlider.tsx
> +              {s.title || s.subtitle ? (
- [ ] Здесь проверку можно и нужно убрать

2022-03-21 12:53 UTC, EvgeniyaFilatova commented on src/common/components/HeroSlider/HeroSlider.tsx
> +                  {s.title ? (
- [ ] Используй условный рендеринг с логическим оператором && (не нужно писать : null)

2022-03-21 12:53 UTC, EvgeniyaFilatova commented on src/common/components/HeroSlider/HeroSlider.tsx
> +                  {s.subtitle ? (
- [ ] Аналогично

2022-03-21 12:53 UTC, EvgeniyaFilatova commented on src/common/components/HeroSlider/HeroSlider.tsx
> +const HeroSlider: FC<HeroSliderProps> = ({ slides, ...rest }) => {
- [ ] А почему такое название выбрал? Slider же можно просто

2022-03-21 12:53 UTC, EvgeniyaFilatova commented on src/common/components/MainMenu/MainMenu.tsx
> +type SocialMediaTypes = 'telegram' | 'facebook' | 'instagram' | undefined;
- [ ] Если есть какие-то общие константы или типы, то лучше выносить их в один файл, из которого будешь импортить их во всех частях приложения. Вот тут вполне такой случай, список соц сетей может еще где-то встретиться

2022-03-21 12:53 UTC, EvgeniyaFilatova commented on src/common/components/MainMenu/MainMenu.tsx
> +interface MainMenuProps extends React.ComponentPropsWithoutRef<'div'> {
- [ ] Нужен ли тут extends?

2022-03-21 12:53 UTC, EvgeniyaFilatova commented on src/common/components/MainMenu/MainMenu.tsx
> +    document.body.style.overflow = isActive ? 'hidden' : '';
- [ ] Лучше вообще инлайн стили не использовать, тем более через useEffect такое делать

2022-03-21 12:53 UTC, EvgeniyaFilatova commented on src/common/components/MainMenu/MainMenu.tsx
> +            {links.map((l) => (
- [ ] Имя переменной должно быть осмысленное

2022-03-21 12:53 UTC, EvgeniyaFilatova commented on src/config.json
> +{
- [ ] Это же просто константы. Переименуй файл в consts.ts какой-нибудь, типизируй массивы, раз используешь ts и экспортируй каждый массив

2022-03-21 12:53 UTC, EvgeniyaFilatova commented on src/layouts/MainLayout/MainLayout.tsx
> +const MainLayout: FC = ({ children }) => {
- [ ] А здесь почему не типизировал пропсы?

2022-03-21 12:53 UTC, EvgeniyaFilatova commented on src/layouts/MainLayout/MainLayout.tsx
> +  const toggleMenu = () => setIsMenuActive(!isMenuActive);
- [ ] В setState можно так же передать функцию, которая получит текущее значение state, используй ее тут
https://ru.reactjs.org/docs/hooks-reference.html#usestate

2022-03-21 12:53 UTC, EvgeniyaFilatova commented on src/routes/index.tsx
> +    component: () => <Home />,
- [ ] Почему функции, а не компоненты сразу?

2022-03-21 12:54 UTC, EvgeniyaFilatova commented
- [ ] Сделай для бокового меню анимацию еще, чтобы плавно влево/вправо скользило

2022-03-21 17:50 UTC, evil-star commented on src/App.tsx
> +  useEffect(() => {
На мобильных браузерах есть шторка, из-за которой бывает неправильно вычисляется vh. В helpbook есть ссылка на статью об этой проблеме ( https://disk.yandex.ru/i/BfUslisO_N0yDA ) , я взял от туда скрипт

2022-03-21 18:10 UTC, evil-star commented on src/common/components/HeroSlider/HeroSlider.tsx
> +  const SlickArrowLeft = ({ currentSlide, slideCount, ...props }: any) => (
Пропсы нужны, я извлекаю нужные пропсы и рест оператором передаю остальные. Если сделать иначе, то библиотека слайдера выводит ошибки в консоль

2022-03-21 18:24 UTC, evil-star commented on src/layouts/MainLayout/MainLayout.tsx
> +const MainLayout: FC = ({ children }) => {
Мне кажется тут типизация пропсов будет излишней, т.к. `children` автоматически типизируется реактом ( https://disk.yandex.ru/i/Qa6XT5sUyiS16w ), а других пропсов нет. Если все-таки нужно типизировать, то подскажите что нужно указать

2022-03-21 19:18 UTC, evil-star commented on src/common/components/MainMenu/MainMenu.tsx
> +interface MainMenuProps extends React.ComponentPropsWithoutRef<'div'> {
Я считаю нужен. Если мы захотим передавать какой-то стандартный пропс, по типу `onClick`, то нам придется его дополнительно типизировать, а этот extends позволяет автоматически протипизировать это

2022-03-21 19:21 UTC, evil-star commented on src/common/components/MainMenu/MainMenu.tsx
> +    document.body.style.overflow = isActive ? 'hidden' : '';
Да, но как иначе запретить скролл для body, при открытом меню?

2022-03-21 19:22 UTC, evil-star commented on src/common/components/HeroSlider/HeroSlider.tsx
> +const HeroSlider: FC<HeroSliderProps> = ({ slides, ...rest }) => {
Потому что уже был импортирован компонент Slider из слика. Решил проблему задав алиас для слик слайдера

2022-03-22 07:21 UTC, EvgeniyaFilatova commented on src/App.tsx
> +  useEffect(() => {
Окей, я только через девтулзы обычно верстку смотрю, про шторку бы даже не подумала)

2022-03-22 07:46 UTC, EvgeniyaFilatova commented on src/common/components/MainMenu/MainMenu.tsx
> +interface MainMenuProps extends React.ComponentPropsWithoutRef<'div'> {
То есть просто на будущее? Ты сейчас в компоненте работаешь именно с теми пропсами, которые типизировал сам, никакие пропсы сверх этого не предусмотрены, их использование в будущем тоже (ты же не собираешь остальные пропсы через ...props). Мне кажется, если будет необходимость в передаче множества стандартных пропсов, то как раз в этот момент добавишь extends, а сейчас это лишнее

2022-03-22 08:09 UTC, EvgeniyaFilatova commented on src/common/components/MainMenu/MainMenu.tsx
> +    document.body.style.overflow = isActive ? 'hidden' : '';
Окей, оставляем

2022-03-22 08:10 UTC, EvgeniyaFilatova commented on src/layouts/MainLayout/MainLayout.tsx
> +const MainLayout: FC = ({ children }) => {
Давай без нее, но если что, то можно типизировать вот так вроде React.ReactElement

2022-03-22 08:27 UTC, EvgeniyaFilatova commented on src/common/components/MainMenu/MainMenu.tsx
> +                {socialItem.type === 'telegram' && <TelegramIcon />}
Наверное, можно саму свгшку тоже хранить в массиве socialMedia и отрисовывать их сразу, тогда условие не нужно будет?

2022-03-22 17:52 UTC, merged